<script setup lang="ts">
import {
  Bell,
  FlaskConical,
  Info,
  Languages,
  Lock,
  Monitor,
  Moon,
  Sun,
  SunMedium,
  Trash2,
} from '@lucide/vue';
import type { Locale } from '@rumbo/route-spec';
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import AppButton from '../components/AppButton.vue';
import LanguageOptions from '../components/LanguageOptions.vue';
import SegmentedControl from '../components/SegmentedControl.vue';
import ToggleSwitch from '../components/ToggleSwitch.vue';
import {
  notificationStatus,
  requestNotifications,
  type NotificationStatus,
} from '../services/notifications.ts';
import { supports } from '../services/platform.ts';
import { forgetDeviceId } from '../services/device.ts';
import { db, local } from '../services/storage.ts';
import { type ThemeSetting, useSettingsStore } from '../stores/settings.ts';
import { useUiStore } from '../stores/ui.ts';

// S12 · Settings. The language uses the same cards as S00 and applies at once,
// without reloading; cards generated by AI stay in their language (ADR 0001).
const { t } = useI18n();
const settings = useSettingsStore();
const ui = useUiStore();

const locale = computed<Locale>({
  get: () => settings.locale ?? 'es',
  set: (value) => {
    settings.locale = value;
  },
});

const themeOptions = computed(() => [
  { value: 'system' as ThemeSetting, label: t('settings.theme.system'), icon: Monitor },
  { value: 'light' as ThemeSetting, label: t('settings.theme.light'), icon: Sun },
  { value: 'dark' as ThemeSetting, label: t('settings.theme.dark'), icon: Moon },
]);
const unitOptions = computed(() => [
  { value: 'metric' as const, label: t('settings.units.metric') },
  { value: 'imperial' as const, label: t('settings.units.imperial') },
]);

const canVibrate = supports.vibration();
const notifications = ref<NotificationStatus>('default');
onMounted(() => {
  notifications.value = notificationStatus();
});
async function enableNotifications(): Promise<void> {
  notifications.value = await requestNotifications();
}

const version = __APP_VERSION__;
const commit = ref<string | null>(null);
onMounted(async () => {
  try {
    const response = await fetch('/version.json', { cache: 'no-store' });
    if (response.ok) commit.value = ((await response.json()) as { commit?: string }).commit ?? null;
  } catch {
    commit.value = null;
  }
});

async function clearData(): Promise<void> {
  const confirmed = await ui.confirm({
    title: { key: 'settings.clearData.title' },
    body: { key: 'settings.clearData.body' },
    confirmLabel: { key: 'settings.clearData.yes' },
    cancelLabel: { key: 'settings.clearData.no' },
    destructive: true,
  });
  if (!confirmed) return;
  await db.clear();
  forgetDeviceId();
  local.remove('rumbo.settings');
  try {
    for (const key of (await globalThis.caches?.keys()) ?? []) await caches.delete(key);
  } catch {
    // No caches to clear.
  }
  // A fresh start: S00 asks for the language again.
  globalThis.location.assign('/welcome');
}
</script>

<template>
  <main class="settings">
    <h1 class="settings__title t-h1">{{ t('settings.title') }}</h1>

    <section class="group" aria-labelledby="s-alerts">
      <h2 id="s-alerts" class="t-caption t-muted">{{ t('settings.sections.alerts') }}</h2>
      <div class="card">
        <div class="row">
          <Bell :size="22" aria-hidden="true" class="row__icon" />
          <span class="row__label">{{ t('settings.sound') }}</span>
          <ToggleSwitch v-model="settings.sound" :label="t('settings.sound')" />
        </div>
        <div v-if="canVibrate" class="row">
          <span class="row__icon" aria-hidden="true" />
          <span class="row__label">{{ t('settings.vibration') }}</span>
          <ToggleSwitch v-model="settings.vibration" :label="t('settings.vibration')" />
        </div>
        <div class="row">
          <span class="row__icon" aria-hidden="true" />
          <span class="row__label">
            {{ t('settings.notifications.label') }}
            <small class="t-small t-muted">
              <template v-if="notifications === 'granted'">{{
                t('settings.notifications.granted')
              }}</template>
              <template v-else-if="notifications === 'denied'">{{
                t('settings.notifications.denied')
              }}</template>
              <template v-else-if="notifications === 'unsupported'">{{
                t('settings.notifications.unsupported')
              }}</template>
            </small>
          </span>
          <AppButton
            v-if="notifications === 'default'"
            variant="secondary"
            size="s"
            @click="enableNotifications"
          >
            {{ t('settings.notifications.enable') }}
          </AppButton>
        </div>
      </div>
    </section>

    <section class="group" aria-labelledby="s-screen">
      <h2 id="s-screen" class="t-caption t-muted">{{ t('settings.sections.screen') }}</h2>
      <div class="card">
        <div class="stack">
          <span class="t-body-strong">{{ t('settings.theme.label') }}</span>
          <SegmentedControl
            v-model="settings.theme"
            :options="themeOptions"
            :label="t('settings.theme.label')"
          />
        </div>
        <div class="row">
          <SunMedium :size="22" aria-hidden="true" class="row__icon" />
          <span class="row__label">
            {{ t('settings.sol.label') }}
            <small class="t-small t-muted">{{ t('settings.sol.hint') }}</small>
          </span>
          <ToggleSwitch v-model="settings.sol" :label="t('settings.sol.label')" />
        </div>
      </div>
    </section>

    <section class="group" aria-labelledby="s-general">
      <h2 id="s-general" class="t-caption t-muted">{{ t('settings.sections.general') }}</h2>
      <div class="card">
        <div class="stack">
          <span class="t-body-strong row__heading"
            ><Languages :size="20" aria-hidden="true" />{{ t('settings.language.label') }}</span
          >
          <LanguageOptions v-model="locale" />
          <p class="t-small t-muted">{{ t('settings.language.hint') }}</p>
        </div>
        <div class="stack">
          <span class="t-body-strong">{{ t('settings.units.label') }}</span>
          <SegmentedControl
            v-model="settings.units"
            :options="unitOptions"
            :label="t('settings.units.label')"
          />
        </div>
      </div>
    </section>

    <section class="group" aria-labelledby="s-privacy">
      <h2 id="s-privacy" class="t-caption t-muted">{{ t('settings.sections.privacy') }}</h2>
      <div class="card">
        <div class="row">
          <Lock :size="22" aria-hidden="true" class="row__icon" />
          <span class="row__label">
            {{ t('settings.analytics.label') }}
            <small class="t-small t-muted">{{ t('settings.analytics.hint') }}</small>
          </span>
          <ToggleSwitch
            :model-value="settings.analyticsConsent === true"
            :label="t('settings.analytics.label')"
            @update:model-value="settings.analyticsConsent = $event"
          />
        </div>
        <AppButton variant="danger" size="m" block @click="clearData">
          <template #icon><Trash2 :size="20" aria-hidden="true" /></template>
          {{ t('settings.clearData.label') }}
        </AppButton>
      </div>
    </section>

    <section class="group" aria-labelledby="s-demo">
      <h2 id="s-demo" class="t-caption t-muted">{{ t('settings.sections.demo') }}</h2>
      <div class="card">
        <div class="row">
          <FlaskConical :size="22" aria-hidden="true" class="row__icon row__icon--sim" />
          <span class="row__label">
            {{ t('settings.simulation.label') }}
            <small class="t-small t-muted">{{ t('settings.simulation.hint') }}</small>
          </span>
          <ToggleSwitch v-model="settings.simulation" :label="t('settings.simulation.label')" />
        </div>
      </div>
    </section>

    <section class="group" aria-labelledby="s-about">
      <h2 id="s-about" class="t-caption t-muted">{{ t('settings.sections.about') }}</h2>
      <div class="card about">
        <p class="row__heading t-body-strong">
          <Info :size="20" aria-hidden="true" />{{ t('settings.version', { version }) }}
          <span v-if="commit && commit !== 'unknown'" class="t-small t-muted"
            >· {{ commit.slice(0, 7) }}</span
          >
        </p>
        <p class="t-small t-muted">{{ t('settings.credits') }}</p>
      </div>
    </section>
  </main>
</template>

<style scoped>
.settings {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 640px;
  margin: 0 auto;
  padding: calc(24px + var(--safe-top)) var(--gutter) 32px;
}
.group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.card {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 16px;
  border: var(--control-border) solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-surface);
}
.row {
  display: flex;
  align-items: center;
  gap: 12px;
  min-height: 48px;
}
.row__icon {
  flex: none;
  width: 22px;
  color: var(--color-text-muted);
}
.row__icon--sim {
  color: var(--color-sim);
}
.row__label {
  display: flex;
  flex: 1;
  flex-direction: column;
  min-width: 0;
  font: 500 16px/22px var(--font-ui);
}
.row__heading {
  display: flex;
  align-items: center;
  gap: 8px;
}
.stack {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.about {
  gap: 8px;
}
</style>
